### ISSUE TITLE
suggestion to add library(rvest) in purrr-magic

### ISSUE THREAD

**Issue by jleslie17** [ctlente/blog#1]
Thanks for the very insightful blog post entitled "The Magic of Purrr"!

To run the pluck() command, I think you need to add a call to library(rvest).

**Comment by ctlente** [comment]
Thanks for the feedback, Jonathan! `rvest` was not included because I'm using the most recent version of `purrr`, where `pluck()` is present (see this [tidyverse article](https://www.tidyverse.org/articles/2017/08/purrr-0.2.3/) for more information).

**Comment by jleslie17** [comment]
Ah, I see. Thanks for the explanation and thanks for the link! Apologies for my ignorance.

And, thanks, again, for the useful post!
